name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - staging
      - production
  pull_request:

jobs:
  quality:
    name: Code Quality and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Set environment variables
        run: |
          echo "VITE_ENV=${{ secrets.VITE_ENV }}" >> $GITHUB_ENV
          echo "VITE_PROD_BASE_URL=${{ secrets.VITE_PROD_BASE_URL }}" >> $GITHUB_ENV
          echo "VITE_DEV_BASE_URL=${{ secrets.VITE_DEV_BASE_URL }}" >> $GITHUB_ENV
          echo "CHROMATIC_PROJECT_TOKEN=${{ secrets.CHROMATIC_PROJECT_TOKEN }}" >> $GITHUB_ENV
      
          
      - name: Run Biome Lint
        run: pnpm format

      - name: Run ESLint
        run: pnpm lint

      - name: Run Unit and Component Tests
        run: pnpm test -- --coverage

      - name: Build Storybook and Deploy to Chromatic
        run: pnpm run chromatic

      - name: Deploy App to Vercel
        run: pnpm exec vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # Wait for Vercel deployment to be live before running tests
      - name: Wait for Vercel deployment to be live
        run: |
          until curl --silent --fail https://smart-pantry-webapp.vercel.app; do
            echo "Waiting for app to be live..."
            sleep 20
          done

      - name: Run End-to-End Tests
        run: pnpm run test:e2e:headless
        env:
          CI: true
