name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - staging
      - production
  pull_request:

jobs:
  quality:
    name: Code Quality and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Biome Lint
        run: pnpm format

      - name: Run ESLint
        run: pnpm lint

      - name: Run Unit and Component Tests
        run: pnpm test -- --coverage

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Deploy Storybook to Vercel
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy App to Vercel
        run: pnpm exec vercel --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # Set environment variable for production (before E2E tests)
      - name: Set environment to production
        run: echo "VITE_ENV=production" >> $GITHUB_ENV

      # Wait for Vercel deployment to be live before running tests
      - name: Wait for Vercel deployment to be live
        run: |
          until curl --silent --fail https://smart-pantry-webapp.vercel.app; do
            echo "Waiting for app to be live..."
            sleep 10
          done

      - name: Run End-to-End Tests
        run: pnpm run test:e2e:headless
        env:
          CI: true
